### ISSUE TITLE
Unity 2018.2.0b2 Bullet.cs `Bullet.HandleCollision()' is marked as an override but no suitable method found to override

### ISSUE THREAD

**Issue by igame3dbill** [NotSoOld/SHUDRS#1]
Assets/SHUDRS-master/Scripts (Destruction)/Weaponry/Bullet.cs(14,23): error CS0115: `Bullet.HandleCollision()' is marked as an override but no suitable method found to override

**Comment by NotSoOld** [comment]
Make sure you have Projectile.cs script in your project, it does contain abstract method HandleCollision().
